---
- name: Fetch instance ID
  uri:
    url: "http://169.254.169.254/latest/meta-data/instance-id"
    return_content: yes
  register: aws_instance_id

- name: Firewall rules
  import_tasks: ufw.yml

- name: Create consul services
  include_tasks: consul-services.yml
  loop: "{{ network_settings | from_json | dict2items }}"

- name: Run certificate tasks
  import_tasks: certs.yml

- name: Create systemd services
  include_tasks: systemd-services.yml
  loop: "{{ network_settings | from_json | dict2items }}"

- name: Reload Consul service
  systemd:
    name: consul
    state: restarted