---
- name: Ensure pip3
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Install jinja2-cli
  pip:
    name: jinja2-cli

- name: Fetch instance ID
  uri:
    url: "http://169.254.169.254/latest/meta-data/instance-id"
    return_content: yes
  register: aws_instance_id

- name: Write deployed networks file
  copy:
    dest: "/home/ubuntu/deployed_networks"
    content: "{{ deployed_networks }}"
    owner: ubuntu
    group: ubuntu
    mode: 0777

- name: Firewall rules
  import_tasks: ufw.yml

- name: Create consul services
  include_tasks: consul-services.yml
  loop: "{{ network_settings | from_json | dict2items }}"

- name: Run certificate tasks
  import_tasks: certs.yml

- name: Create systemd services
  include_tasks: systemd-services.yml
  loop: "{{ network_settings | from_json | dict2items }}"

- name: Reload Consul service
  systemd:
    name: consul
    state: restarted